server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://daisen_win64:3306/activiti_learn?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  # activiti default configuration
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
    # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full
